### ISSUE TITLE
Underground bases blocked from spawning

### ISSUE THREAD

**Issue by adrsquared** [MeridiusIX/Modular-Encounters-Systems#102]
I'm currently making use of the ability to spawn bases deep underground as part of a campaign mod (accessed them via teleporters). But now there appears to be a universal altitude check to block all spawns below altitude -1000 that can't be disabled. Was hoping that check might be set up with a flag to disable it.

**Comment by MeridiusIX** [comment]
I don't plan to change anything related to that, since things seem to get confused at those depths.

You may be able to get around the issue using static encounters however. The area where the spawn is triggered and the position of where the encounter actually appears can be configured differently. The 1000m check should only look at the spawn source location (eg player, ai block, etc) when making the restrictions.

**Comment by adrsquared** [comment]
I've tried both having the offset in the Prefab def in the SpawnGroup and the RelativeSpawnOffset inside of the [RivalAI Spawn] definition. Both get blocked by that check.

The setup has one base spawn as a Planetary Installation, which then spawns its counterpart bases deeper underground via its RAI behavior (to stagger the spawns so that the game doesn't freeze up from all of the massive grid spawns). I'm not sure what you mean by static encounters.

**Comment by adrsquared** [comment]
Looks like I found a hack that works. Needed to put the offset in the Prefab def in the SpawnGroup, set the RelativeSpawnOffset to {0,0,0}, and set the SkipVoxelSpawnChecks and SkipGridSpawnChecks to true in the SpawnGroup to get around the path checking.
