### ISSUE TITLE
Log level change request for Selective Physics/SyncDistance condition

### ISSUE THREAD

**Issue by kontu** [MeridiusIX/Modular-Encounters-Systems#244]
Got myself stuck for 2 days not being able to figure out why MES wouldn't respond to commands on a dev torch instance I was working on; when I remembered about the sync distance thing. Given that the mod is entirely disabled if this condition is met; could this be changed from INFO to ERROR?  

I do know it's documented in the troubleshooting section, but having it as an error would have made me found it myself during log parsing.

```
06:53:27.1315 [INFO]   Keen:    MES Spawner / Startup: Mod Disabled: Selective Physics Updates is Enabled with SyncDistance Less Than 10000
06:53:27.1315 [INFO]   Keen:    MES Spawner / Startup: Disable Selective Physics Updates OR Increase SyncDistance To Minimum of 10000
```

**Comment by MeridiusIX** [comment]
If you're talking about the tag that specifically says `[INFO]`, that is something that torch adds. It's not present in vanilla logging. Regardless, I have no intention of introducing any text that uses `Error` for this, since it is expected behavior. For my purposes, `Error` text is reserved for unexpected behavior.
